// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RepoLens.Infrastructure.Persistence;

#nullable disable

namespace RepoLens.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RepoLensDbContext))]
    partial class RepoLensDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RepoLens.Domain.Discovery.Repository", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultBranch")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("default_branch");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("DiscoveredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovered_at_utc");

                    b.Property<int>("Forks")
                        .HasColumnType("integer")
                        .HasColumnName("forks");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("full_name");

                    b.Property<long>("GitHubId")
                        .HasColumnType("bigint")
                        .HasColumnName("github_id");

                    b.Property<string>("HtmlUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("html_url");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<bool>("IsFork")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fork");

                    b.Property<string>("LicenseSpdx")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("license_spdx");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("OpenIssues")
                        .HasColumnType("integer")
                        .HasColumnName("open_issues");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("owner");

                    b.Property<string>("PrimaryLanguage")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("primary_language");

                    b.Property<DateTimeOffset?>("PushedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pushed_at");

                    b.Property<int>("Stars")
                        .HasColumnType("integer")
                        .HasColumnName("stars");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.HasIndex("GitHubId")
                        .IsUnique();

                    b.ToTable("repositories", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
